vich_uploader:
    db_driver: orm

    mappings:
        association:
            uri_prefix:         /images/association
            upload_destination: '%kernel.project_dir%/public/images/association'
            namer:              vich_clean_namer
        profile:
            uri_prefix:         /images/profile
            upload_destination: '%kernel.project_dir%/public/images/profile'
            namer:              vich_clean_namer
